---

# We need sudo so that Docker is installed as a service.
sudo: required

services: 
  - docker

env:
  - DB_USERNAME=postgres
    DB_PASSWORD=postgres
    DB_HOSTNAME=postgres

before_install:
  - sudo service postgresql stop
  - docker build --target base -t phoenix-base:latest .
  - docker ps -a

script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run test mix deps.get
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run test mix test
  