---

# We need sudo so that Docker is installed as a service.
sudo: required

services: 
  - docker

# env:
  # - DOCKER_COMPOSE_VERSION=1.19.0
  # - MIX_ENV=test

before_install:
  - sudo service postgresql stop
  - docker build --target base -t phoenix_test:latest .
  - docker ps -a
  # - docker run phoenix_test mix deps.get

#   - sudo rm /usr/local/bin/docker-compose
#   - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#   - chmod +x docker-compose
#   - sudo mv docker-compose /usr/local/bin

script:
  # - docker-compose run phoenix mix deps.get
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run test mix deps.get
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run test mix test
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run -w /app/assets test yarn list # change this to command to run jest tests for frontend once they are added
  # - docker-compose -f docker-compose.yml -f docker-compose.test.yml run test bash -c "mix deps.get && mix test"