version: '3.3'

services:
  test:
    image: phoenix_test
    environment:
      - MIX_ENV=test
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOSTNAME
    volumes:
      - .:/app
    depends_on:
      - postgres