version: '3.3'

services:
  phoenix:
    image: phoenix-base
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      # - DB_USERNAME=${DB_USERNAME}
      # - DB_PASSWORD=${DB_PASSWORD}
      # - DB_HOSTNAME=${DB_HOSTNAME}
    ports:
        - "4000:4000"
        - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/assets/node_modules 
    depends_on:
      - postgres

  postgres:
    image: postgres:10.2
    volumes: 
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: 
  node_modules: