version: '3.3'

services:
  test:
    image: phoenix_test
    environment:
      - MIX_ENV=test
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOSTNAME=localhost
    volumes:
      - .:/app
    depends_on:
      - postgres